### PR TITLE
Feature/full walls and B/D in one move

### PR DESCRIPTION
**Pull request by brooklyn-omniheurists**

### CODE REVIEW

**Comment by mayanks43** [comment]
Any reason why this isn't merged yet?

**Comment by brooklyn-omniheurists** [comment]
About to push UI.

**Comment by brooklyn-omniheurists** [comment]
@mayanks43 Actually, we'll push that in the next PR, we'll merge this after the next commit

**Comment by mayanks43** [comment]
:v:

**Pull request merged**
